entities:
- name: mysql_container_deployment
  namespace: laplacian.arch.deployment.component.mysql
  supertype_name: db_container_deployment
  supertype_namespace: laplacian.arch.deployment.container

  properties:
  - name: port
    type: number
    optional: true
    default_value: |
      3306

  - name: jdbc_driver_jar
    type: string
    optional: true
    default_value: |
      "mysql:mysql-connector-java:8.0.23"

  - name: jdbc_connection_string
    type: string
    snippet: |
      "jdbc:mysql://${instanceName}/${databaseName}"

  - name: jdbc_driver_class_name
    type: string
    optional: true
    default_value: |
      "com.mysql.jdbc.Driver"