entities:
- name: oracle_jdbc_datasource_configuration
  namespace: laplacian.arch.deployment.datasource
  supertype_name: jdbc_datasource_configuration
  supertype_namespace: laplacian.arch.deployment.datasource
  subtype_key_value: oracle_jdbc

  properties:
  - name: driver_class_name
    type: string
    optional: true
    default_value: |
      "oracle.jdbc.OracleDriver"
