#!/usr/bin/env bash

set -e

VERSION='1.0.0'
GROUP='laplacian-arch'

PROJECT_BASE_DIR=$(cd $"${BASH_SOURCE%/*}/../" && pwd)
SUBPROJECTS_DIR="$PROJECT_BASE_DIR/subprojects"
DIST_DIR="$PROJECT_BASE_DIR/dist"
LAPLACIAN_HOME="$HOME/.laplacian"
LAPLACIAN_CACHE_DIR="$LAPLACIAN_HOME/cache"

BACKEND_API_DOMAIN_MODEL_MODULE_NAME='backend-api-domain-model'
BACKEND_API_DOMAIN_MODEL_DIR="$SUBPROJECTS_DIR/$BACKEND_API_DOMAIN_MODEL_MODULE_NAME"
BACKEND_API_DOMAIN_MODEL_MODULE_PATH="$DIST_DIR/$GROUP.$BACKEND_API_DOMAIN_MODEL_MODULE_NAME-$VERSION.zip"

BACKEND_API_DOMAIN_MODEL_PLUGIN_MODULE_NAME="$BACKEND_API_DOMAIN_MODEL_MODULE_NAME-plugin"
BACKEND_API_DOMAIN_MODEL_PLUGIN_DIR="$SUBPROJECTS_DIR/$BACKEND_API_DOMAIN_MODEL_PLUGIN_MODULE_NAME"
BACKEND_API_DOMAIN_MODEL_PLUGIN_PATH="$DIST_DIR/$GROUP.$BACKEND_API_DOMAIN_MODEL_PLUGIN_MODULE_NAME-$VERSION.jar"
BACKEND_API_DOMAIN_MODEL_PLUGIN_BUILT_MODULE="$BACKEND_API_DOMAIN_MODEL_PLUGIN_DIR/build/libs/$GROUP.$BACKEND_API_DOMAIN_MODEL_PLUGIN_MODULE_NAME-$VERSION.jar"

DEPLOYMENT_DOMAIN_MODEL_MODULE_NAME='deployment-domain-model'
DEPLOYMENT_DOMAIN_MODEL_DIR="$SUBPROJECTS_DIR/$DEPLOYMENT_DOMAIN_MODEL_MODULE_NAME"
DEPLOYMENT_DOMAIN_MODEL_MODULE_PATH="$DIST_DIR/$GROUP.$DEPLOYMENT_DOMAIN_MODEL_MODULE_NAME-$VERSION.zip"

DEPLOYMENT_DOMAIN_MODEL_PLUGIN_MODULE_NAME="$DEPLOYMENT_DOMAIN_MODEL_MODULE_NAME-plugin"
DEPLOYMENT_DOMAIN_MODEL_PLUGIN_DIR="$SUBPROJECTS_DIR/$DEPLOYMENT_DOMAIN_MODEL_PLUGIN_MODULE_NAME"
DEPLOYMENT_DOMAIN_MODEL_PLUGIN_PATH="$DIST_DIR/$GROUP.$DEPLOYMENT_DOMAIN_MODEL_PLUGIN_MODULE_NAME-$VERSION.jar"
DEPLOYMENT_DOMAIN_MODEL_PLUGIN_BUILT_MODULE="$DEPLOYMENT_DOMAIN_MODEL_PLUGIN_DIR/build/libs/$GROUP.$DEPLOYMENT_DOMAIN_MODEL_PLUGIN_MODULE_NAME-$VERSION.jar"

BACKEND_API_SPRINGBOOT2_SERVICE_TEMPLATE_MODULE_NAME='backend-api-springboot2-service-template'
BACKEND_API_SPRINGBOOT2_SERVICE_TEMPLATE_DIR="$SUBPROJECTS_DIR/$BACKEND_API_SPRINGBOOT2_SERVICE_TEMPLATE_MODULE_NAME"
BACKEND_API_SPRINGBOOT2_SERVICE_TEMPLATE_MODULE_PATH="$DIST_DIR/$GROUP.$BACKEND_API_SPRINGBOOT2_SERVICE_TEMPLATE_MODULE_NAME-$VERSION.zip"

BACKEND_API_PROJECT_TEMPLATE_MODULE_NAME='backend-api-project-template'
BACKEND_API_PROJECT_TEMPLATE_DIR="$SUBPROJECTS_DIR/$BACKEND_API_PROJECT_TEMPLATE_MODULE_NAME"
BACKEND_API_PROJECT_TEMPLATE_MODULE_PATH="$DIST_DIR/$GROUP.$BACKEND_API_PROJECT_TEMPLATE_MODULE_NAME-$VERSION.zip"

DATASET_FLYWAY_MIGRATION_TEMPLATE_MODULE_NAME='dataset-flyway-migration-template'
DATASET_FLYWAY_MIGRATION_TEMPLATE_DIR="$SUBPROJECTS_DIR/$DATASET_FLYWAY_MIGRATION_TEMPLATE_MODULE_NAME"
DATASET_FLYWAY_MIGRATION_TEMPLATE_MODULE_PATH="$DIST_DIR/$GROUP.$DATASET_FLYWAY_MIGRATION_TEMPLATE_MODULE_NAME-$VERSION.zip"

METAMODEL_MODEL_URL="https://github.com/nabla-squared/laplacian.core/releases/download/v1.0.0/laplacian-core.metamodel-model-1.0.0.zip"
METAMODEL_PLUGIN_URL="https://github.com/nabla-squared/laplacian.core/releases/download/v1.0.0/laplacian-core.metamodel-plugin-1.0.0.jar"
DOMAIN_MODEL_PLUGIN_TEMPLATE_URL="https://github.com/nabla-squared/laplacian.core/releases/download/v1.0.0/laplacian-core.domain-model-plugin-template-1.0.0.zip"

GRADLE="./gradlew"
ZIP="jar -cfM"

main() {
  # set -x
  generate_backend_api_domain_model_plugin_src || die
  build_backend_api_domain_model_plugin || die
  generate_deployment_domain_model_plugin_src || die
  build_deployment_domain_model_plugin || die
  update_distribution || die
  update_local_modules || die
}

die() {
  echo "$0 FAILED!!" 1>&2
  exit 1
}

generate_backend_api_domain_model_plugin_src() {
  rm -rf $BACKEND_API_DOMAIN_MODEL_PLUGIN_DIR && \
  mkdir -p $BACKEND_API_DOMAIN_MODEL_PLUGIN_DIR && \
  laplacian generate \
    --template $DOMAIN_MODEL_PLUGIN_TEMPLATE_URL \
    --model $BACKEND_API_DOMAIN_MODEL_DIR \
    --model $METAMODEL_MODEL_URL \
    --plugin $METAMODEL_PLUGIN_URL \
    --destination $BACKEND_API_DOMAIN_MODEL_PLUGIN_DIR
}

build_backend_api_domain_model_plugin() {
  (cd $BACKEND_API_DOMAIN_MODEL_PLUGIN_DIR
    $GRADLE build
  ) &&
  cp -f $BACKEND_API_DOMAIN_MODEL_PLUGIN_BUILT_MODULE $LAPLACIAN_CACHE_DIR
}

generate_deployment_domain_model_plugin_src() {
  rm -rf $DEPLOYMENT_DOMAIN_MODEL_PLUGIN_DIR && \
  mkdir -p $DEPLOYMENT_DOMAIN_MODEL_PLUGIN_DIR && \
  laplacian generate \
    --template $DOMAIN_MODEL_PLUGIN_TEMPLATE_URL \
    --model $DEPLOYMENT_DOMAIN_MODEL_DIR \
    --model $METAMODEL_MODEL_URL \
    --model $BACKEND_API_DOMAIN_MODEL_DIR \
    --plugin $METAMODEL_PLUGIN_URL \
    --plugin $BACKEND_API_DOMAIN_MODEL_PLUGIN_BUILT_MODULE \
    --destination $DEPLOYMENT_DOMAIN_MODEL_PLUGIN_DIR
}

build_deployment_domain_model_plugin() {
  (cd $DEPLOYMENT_DOMAIN_MODEL_PLUGIN_DIR
    $GRADLE build
  )
}

update_distribution() {
  rm -rf $DIST_DIR && \
  mkdir -p $DIST_DIR && \
  cp -f $BACKEND_API_DOMAIN_MODEL_PLUGIN_BUILT_MODULE $BACKEND_API_DOMAIN_MODEL_PLUGIN_PATH && \
  (cd $BACKEND_API_DOMAIN_MODEL_DIR
    $ZIP $BACKEND_API_DOMAIN_MODEL_MODULE_PATH .
  ) && \
  cp -f $DEPLOYMENT_DOMAIN_MODEL_PLUGIN_BUILT_MODULE $DEPLOYMENT_DOMAIN_MODEL_PLUGIN_PATH && \
  (cd $DEPLOYMENT_DOMAIN_MODEL_DIR
    $ZIP $DEPLOYMENT_DOMAIN_MODEL_MODULE_PATH .
  ) && \
  (cd $BACKEND_API_SPRINGBOOT2_SERVICE_TEMPLATE_DIR
    $ZIP $BACKEND_API_SPRINGBOOT2_SERVICE_TEMPLATE_MODULE_PATH .
  ) && \
  (cd $BACKEND_API_PROJECT_TEMPLATE_DIR
    $ZIP $BACKEND_API_PROJECT_TEMPLATE_MODULE_PATH .
  ) && \
  (cd $DATASET_FLYWAY_MIGRATION_TEMPLATE_DIR
    $ZIP $DATASET_FLYWAY_MIGRATION_TEMPLATE_MODULE_PATH .
  )
}

update_local_modules() {
  mkdir -p $LAPLACIAN_CACHE_DIR && \
  cp -f \
    $BACKEND_API_DOMAIN_MODEL_PLUGIN_PATH \
    $BACKEND_API_DOMAIN_MODEL_MODULE_PATH \
    $DEPLOYMENT_DOMAIN_MODEL_PLUGIN_PATH \
    $DEPLOYMENT_DOMAIN_MODEL_MODULE_PATH \
    $BACKEND_API_SPRINGBOOT2_SERVICE_TEMPLATE_MODULE_PATH \
    $BACKEND_API_PROJECT_TEMPLATE_MODULE_PATH \
    $DATASET_FLYWAY_MIGRATION_TEMPLATE_MODULE_PATH \
    $LAPLACIAN_CACHE_DIR
}

main