entities:
- name: postgres_container_deployment
  namespace: laplacian.arch.deployment.component.postgres
  supertype_name: db_container_deployment
  supertype_namespace: laplacian.arch.deployment.container

  properties:
  - name: port
    type: number
    optional: true
    default_value: |
      5432

  - name: jdbc_driver_jar
    type: string
    optional: true
    default_value: |
      "org.postgresql:postgresql:42.2.18"

  - name: jdbc_connection_string
    type: string
    snippet: |
      "jdbc:postgresql://${instanceName}/${databaseName}"

  - name: jdbc_driver_class_name
    type: string
    optional: true
    default_value: |
      "org.postgresql.Driver"