entities:
- name: heap_memory_cache_policy
  namespace: laplacian.arch.backend.api.cache
  supertype_name: cache_policy
  supertype_namespace: laplacian.arch.backend.api.cache
  subtype_key_value: heap

